[package]
name = "rust-terminal-app-template"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.1", features = ["derive"] }
log = "0.4.20"
log4rs = "1.3.0"
chrono = "0.4.34"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
